AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket with optional configurations.
Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket.
    Default: 'hchitrad-43132121'
  EnableVersioning:
    Type: String
    AllowedValues:
    - Enabled
    - Suspended
    Default: 'Suspended'
    Description: Enable versioning for the S3 bucket.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketName
      VersioningConfiguration:
        Status:
          Ref: EnableVersioning
  
 
